/* eslint-disable */

/*
https://curl.haxx.se/docs/manpage.html
http://www.mit.edu/afs.new/sipb/user/ssen/src/curl-7.11.1/docs/curl.html
https://github.com/tj/parse-curl.js/blob/master/index.js
*/

const t = {
	Boolean: Boolean,
	String: String,
	Number: Number,
	Array: Array, // <String> requires 'separator'
	Object: Object // <String, String> requires 'keySeparator', 'valueSeparator'
};

const args = {
	"abstract-unix-socket": { type: t.String, arg: "path", since: "7.53.0" },
	"alt-svc": { type: t.String, arg: "file name", since: "7.64.1" },
	anyauth: { type: t.Boolean, since: "7.10.6" },
	append: { type: t.Boolean, aliases: ["a"] },
	basic: { type: t.Boolean, since: "7.10.6" },
	cacert: { type: t.String, arg: "file" },
	capath: { type: t.String, arg: "dir" },
	"cert-status": { type: t.Boolean, since: "7.41.0" },
	"cert-type": { type: t.String, arg: "type" },
	cert: {
		type: t.Array,
		separator: ":",
		aliases: ["E"],
		arg: "certificate[:password]"
	},
	ciphers: { type: t.Array, separator: ":", arg: "list of ciphers" },
	"compressed-ssh": { type: t.Boolean, since: "7.56.0" },
	compressed: { type: t.Boolean },
	config: { type: t.String, aliases: ["K"], arg: "file", multi: true },
	"connect-timeout": { type: t.Number, arg: "seconds" },
	"connect-to": {
		type: t.Array,
		separator: ":",
		arg: "HOST1:PORT1:HOST2:PORT2",
		since: "7.49.0"
	},
	"continue-at": { type: t.Number, aliases: ["C"], arg: "offset" },
	"cookie-jar": { type: t.String, aliases: ["c"], arg: "filename" },
	cookie: {
		type: t.Object,
		keySeparator: ";",
		valueSeparator: "=",
		aliases: ["b"],
		arg: "data|filename"
	},
	"create-dirs": { type: t.Boolean },
	crlf: { type: t.Boolean, since: "7.40.0" },
	crlfile: { type: t.String, arg: "file", since: "7.19.7" },
	"data-binary": { type: t.String, arg: "data" },
	"data-raw": { type: t.String, arg: "data", since: "7.43.0" },
	"data-urlencode": { type: t.String, arg: "data", since: "7.18.0" },
	data: { type: t.String, aliases: ["d", "data-ascii"], arg: "data" },
	delegation: { type: t.String, arg: "LEVEL" },
	digest: { type: t.Boolean, since: "7.10.6" },
	"disable-eprt": { type: t.Boolean },
	"disable-epsv": { type: t.Boolean },
	disable: { type: t.Boolean, aliases: ["q"] },
	"disallow-username-in-url": { type: t.Boolean, since: "7.61.0" },
	"dns-interface": { type: t.String, arg: "interface", since: "7.33.0" },
	"dns-ipv4-addr": { type: t.String, arg: "address", since: "7.33.0" },
	"dns-ipv6-addr": { type: t.String, arg: "address", since: "7.33.0" },
	"dns-servers": {
		type: t.Array,
		separator: ",",
		arg: "addresses",
		since: "7.33.0"
	},
	"doh-url": { type: t.String, arg: "url", since: "7.62.0" },
	"dump-header": { type: t.String, aliases: ["D"], arg: "filename" },
	"egd-file": { type: t.String, arg: "file" },
	engine: { type: t.String, arg: "name" },
	environment: { type: t.Boolean, deprecated: true },
	"etag-compare": { type: t.String, arg: "file", since: "7.68.0" },
	"etag-save": { type: t.String, arg: "file", since: "7.68.0" },
	"expect100-timeout": { type: t.Number, arg: "seconds", since: "7.47.0" },
	"fail-early": { type: t.Boolean, since: "7.52.0" },
	fail: { type: t.Boolean, aliases: ["f"] },
	"false-start": { type: t.Boolean, since: "7.42.0" },
	"form-string": {
		type: t.Array,
		separator: "=",
		arg: "name=value",
		multi: true
	},
	form: {
		type: t.Array,
		separator: "=",
		aliases: ["F"],
		arg: "name=content",
		multi: true
	},
	"ftp-account": { type: t.String, arg: "data", since: "7.13.0" },
	"ftp-alternative-to-user": {
		type: t.String,
		arg: "command",
		since: "7.15.5"
	},
	"ftp-create-dirs": { type: t.Boolean, since: "7.10.7" },
	"ftp-method": { type: t.String, arg: "method", since: "7.15.1" },
	"ftp-pasv": { type: t.Boolean, since: "7.11.0" },
	"ftp-port": { type: t.String, aliases: ["P"], arg: "address" },
	"ftp-pret": { type: t.Boolean, since: "7.20.0" },
	"ftp-skip-pasv-ip": { type: t.Boolean, since: "7.14.2" },
	"ftp-ssl-ccc-mode": {
		type: t.String,
		arg: "active/passive",
		since: "7.16.2"
	},
	"ftp-ssl-ccc": { type: t.Boolean, since: "7.16.2" },
	"ftp-ssl-control": { type: t.Boolean, since: "7.16.0" },
	"ftp-ssl": { type: t.Boolean, since: "7.11.0", deprecated: true },
	get: { type: t.Boolean, aliases: ["G"] },
	globoff: { type: t.Boolean, aliases: ["g"] },
	"happy-eyeballs-timeout-ms": {
		type: t.Number,
		arg: "milliseconds",
		since: "7.59.0"
	},
	"haproxy-protocol": { type: t.Boolean, since: "7.60.0" },
	head: { type: t.Boolean, aliases: ["I"] },
	header: {
		type: t.Array,
		separator: ": ",
		aliases: ["H"],
		arg: "header",
		multi: true
	},
	help: { type: t.Boolean, aliases: ["h"] },
	"http0.9": { type: t.Boolean, since: "7.66.0" },
	"http1.0": { type: t.Boolean, aliases: ["0"] },
	"http1.1": { type: t.Boolean, since: "7.33.0" },
	"http2-prior-knowledge": { type: t.Boolean, since: "7.49.0" },
	http2: { type: t.Boolean, since: "7.33.0" },
	http3: { type: t.Boolean, since: "7.66.0" },
	"ignore-content-length": { type: t.Boolean, since: "7.46.0" },
	include: { type: t.Boolean, aliases: ["i"] },
	insecure: { type: t.Boolean, aliases: ["k"] },
	interface: { type: t.String, arg: "name" },
	ipv4: { type: t.Boolean, aliases: ["4"], since: "7.10.8" },
	ipv6: { type: t.Boolean, aliases: ["6"], since: "7.10.8" },
	"junk-session-cookies": { type: t.Boolean, aliases: ["j"], since: "7.9.7" },
	"keepalive-time": { type: t.Number, arg: "seconds", since: "7.18.0" },
	"key-type": { type: t.String, arg: "type" },
	key: { type: t.String, arg: "key" },
	krb: { type: t.String, aliases: ["krb4"], arg: "level" },
	"libcurl <file>": {},
	"limit-rate": { type: t.String, arg: "speed", since: "7.10.0" },
	"list-only": { type: t.Boolean, aliases: ["l"] },
	"local-port <num/range>": {},
	"location-trusted": { type: t.Boolean },
	location: { type: t.Boolean, aliases: ["L"] },
	"login-options <options>": {},
	"mail-auth <address>": {},
	"mail-from <address>": {},
	"mail-rcpt-allowfails": {},
	"mail-rcpt <address>": {},
	manual: { type: t.Boolean, aliases: ["M"] },
	"max-filesize": { type: t.Number, arg: "bytes" },
	"max-redirs": { type: t.Number, aliases: ["Z"], arg: "num" },
	"max-time": { type: t.Number, aliases: ["m"], arg: "seconds" },
	metalink: {},
	negotiate: { type: t.Boolean, since: "7.10.6" },
	"netrc-file <filename>": {},
	"netrc-optional": { type: t.Boolean },
	netrc: { type: t.Boolean, aliases: ["n"] },
	next: {},
	"no-alpn": {},
	"no-buffer": { type: t.Boolean, aliases: ["N"] },
	"no-keepalive": {},
	"no-npn": {},
	"no-progress-meter": {},
	"no-sessionid": {},
	"noproxy <no-proxy-list>": {},
	"ntlm-wb": {},
	ntlm: { type: t.Boolean, since: "7.10.6" },
	"oauth2-bearer <token>": {},
	output: { type: t.String, aliases: ["o"], arg: "file" },
	"parallel-immediate": {},
	"parallel-max": {},
	parallel: {},
	pass: { type: t.String, arg: "phrase" },
	"path-as-is": {},
	"pinnedpubkey <hashes>": {},
	post301: {},
	post302: {},
	post303: {},
	"preproxy [protocol://]host[:port]": {},
	"progress-bar": { type: t.Boolean, aliases: ["#"] },
	"proto-default <protocol>": {},
	"proto-redir <protocols>": {},
	"proto <protocols>": {},
	"proxy-anyauth": {},
	"proxy-basic": {},
	"proxy-cacert <file>": {},
	"proxy-capath <dir>": {},
	"proxy-cert-type <type>": {},
	"proxy-cert <cert[:passwd]>": {},
	"proxy-ciphers <list>": {},
	"proxy-crlfile <file>": {},
	"proxy-digest": {},
	"proxy-header <header/@file>": {},
	"proxy-insecure": {},
	"proxy-key-type <type>": {},
	"proxy-key <key>": {},
	"proxy-negotiate": {},
	"proxy-ntlm": { type: t.Boolean },
	"proxy-pass <phrase>": {},
	"proxy-pinnedpubkey <hashes>": {},
	"proxy-service-name <name>": {},
	"proxy-ssl-allow-beast": {},
	"proxy-tls13-ciphers <ciphersuite list>": {},
	"proxy-tlsauthtype <type>": {},
	"proxy-tlspassword <string>": {},
	"proxy-tlsuser <name>": {},
	"proxy-tlsv1": {},
	"proxy-user": {
		type: t.Array,
		separator: ":",
		aliases: ["U"],
		arg: "user:password"
	},
	proxy: {
		type: t.Array,
		separator: ":",
		aliases: ["x"],
		arg: "[protocol://]host[:port]"
	},
	"proxy1.0 <host[:port]>": {},
	proxytunnel: { type: t.Boolean, aliases: ["p"] },
	"pubkey <key>": {},
	quote: { type: t.String, aliases: ["Q"], arg: "command", multi: true },
	"random-file": { type: t.String, arg: "file" },
	range: { type: t.String, aliases: ["r"], arg: "range" },
	raw: { type: t.Boolean, since: "7.16.2" },
	referer: { type: t.String, aliases: ["e"], arg: "URL" },
	"remote-header-name": { type: t.Boolean, aliases: ["J"] },
	"remote-name-all": { type: t.Boolean, since: "7.19.0" },
	"remote-name": { type: t.Boolean, aliases: ["O"] },
	"remote-time": { type: t.Boolean, aliases: ["R"] },
	"request-target": { type: t.Boolean, since: "7.55.0" },
	request: { type: t.String, aliases: ["X"], arg: "command" },
	"resolve <host:port:address[,address]...>": {},
	"retry-connrefused": { type: t.Boolean, since: "7.52.0" },
	"retry-delay <seconds>": {},
	"retry-max-time <seconds>": {},
	"retry <num>": {},
	"sasl-authzid": { type: t.Boolean, since: "7.66.0" },
	"sasl-ir": { type: t.Boolean, since: "7.31.0" },
	"service-name <name>": {},
	"show-error": { type: t.Boolean, aliases: ["S"] },
	silent: { type: t.Boolean, aliases: ["s"] },
	"socks4 <host[:port]>": {},
	"socks4a <host[:port]>": {},
	"socks5-basic": { type: t.Boolean, since: "7.55.0" },
	"socks5-gssapi-nec": {},
	"socks5-gssapi-service <name>": {},
	"socks5-gssapi": { type: t.Boolean, since: "7.55.0" },
	"socks5-hostname <host[:port]>": {},
	"socks5 <host[:port]>": {},
	socks: {
		type: t.Array,
		separator: ":",
		arg: "host[:port]",
		since: "7.11.1",
		deprecated: true
	},
	"speed-limit": { type: t.Number, aliases: ["Y"], arg: "speed" },
	"speed-time": { type: t.Number, aliases: ["y"], arg: "seconds" },
	"ssl-allow-beast": { type: t.Boolean, since: "7.25.0" },
	"ssl-no-revoke": { type: t.Boolean, since: "7.44.0" },
	"ssl-reqd": { type: t.Boolean, since: "7.20.0" },
	"ssl-revoke-best-effort": { type: t.Boolean, since: "7.70.0" },
	ssl: { type: t.Boolean, since: "7.20.0" },
	sslv2: { type: t.Boolean, aliases: ["2"] },
	sslv3: { type: t.Boolean, aliases: ["3"] },
	stderr: { type: t.String, arg: "file" },
	"styled-output": { type: t.Boolean, since: "7.61.0" },
	"suppress-connect-headers": { type: t.Boolean },
	"tcp-fastopen": { type: t.Boolean, since: "7.49.0" },
	"tcp-nodelay": { type: t.Boolean, since: "7.11.2" },
	"telnet-option": { type: t.String, aliases: ["t"], arg: "opt=val" },
	"tftp-blksize <value>": {},
	"tftp-no-options": { type: t.Boolean, since: "7.48.0" },
	"time-cond": { type: t.String, aliases: ["z"], arg: "date expression" },
	"tls-max <VERSION>": {},
	"tls13-ciphers <list of TLS 1.3 ciphersuites>": {},
	"tlsauthtype <type>": {},
	tlspassword: { type: t.Boolean, since: "7.21.4" },
	"tlsuser <name>": {},
	"tlsv1.0": { type: t.Boolean, since: "7.34.0" },
	"tlsv1.1": { type: t.Boolean, since: "7.34.0" },
	"tlsv1.2": { type: t.Boolean, since: "7.34.0" },
	"tlsv1.3": { type: t.Boolean, since: "7.52.0" },
	tlsv1: { type: t.Boolean, aliases: ["1"] },
	"tr-encoding": { type: t.Boolean, since: "7.21.6" },
	"trace-ascii": { type: t.String, arg: "file", since: "7.9.7" },
	"trace-time": { type: t.Boolean, since: "7.14.0" },
	trace: { type: t.String, arg: "file", since: "7.9.7" },
	"unix-socket <path>": {},
	"upload-file": { type: t.String, aliases: ["T"], arg: "file" },
	url: { type: t.String, arg: "URL", multi: true },
	"use-ascii": { type: t.Boolean, aliases: ["B"] },
	"user-agent": { type: t.String, aliases: ["A"], arg: "agent string" },
	user: { type: t.Array, separator: ":", aliases: ["u"], arg: "user:password" },
	verbose: { type: t.Boolean, aliases: ["v"] },
	version: { type: t.Boolean, aliases: ["V"] },
	"write-out": { type: t.String, aliases: ["w"], arg: "format" },
	xattr: { type: t.Boolean }
};
